const $=id=>document.getElementById(id);const reg=$('registrationScreen'),game=$('gameScreen'),form=$('registerForm'),spinBtn=$('spinBtn'),canvas=$('wheelCanvas'),ctx=canvas.getContext('2d'),overlay=$('winnerOverlay'),winnerPrize=$('winnerPrize'),fx=$('fxCanvas'),fctx=fx.getContext('2d');let W=fx.width=innerWidth,H=fx.height=innerHeight;addEventListener('resize',()=>{W=fx.width=innerWidth;H=fx.height=innerHeight});
const prizes=[{name:'YONO',color:'#00a7e1',count:20},{name:'Hand Fan',color:'#ff9f00',count:15},{name:'Battery Fan',color:'#e91e63',count:10},{name:'Bag Pack',color:'#2db84d',count:5},{name:'MYSTERY',color:'#ffffff',count:1,mystery:true}];
const total=51,sections=Array(total).fill(null);sections[0]={...prizes[4]};[10,20,30,40,50].forEach(i=>sections[i]={...prizes[3]});[5,9,14,19,24,29,34,39,44,48].forEach(i=>sections[i]={...prizes[2]});[2,4,7,12,16,18,22,26,28,32,36,38,41,43,46].forEach(i=>sections[i]={...prizes[1]});for(let i=0;i<total;i++)if(!sections[i])sections[i]={...prizes[0]};
const arc=Math.PI*2/total;let rotation=0,spinning=false,particles=[];
function drawWheel(){const r=canvas.width/2;ctx.clearRect(0,0,canvas.width,canvas.height);for(let i=0;i<total;i++){const s=sections[i],a=i*arc-Math.PI/2;ctx.beginPath();ctx.moveTo(r,r);ctx.arc(r,r,r-12,a,a+arc);ctx.closePath();let g=ctx.createRadialGradient(r,r,80,r,r,r);if(s.mystery){g.addColorStop(0,'#fff');g.addColorStop(.35,'#ffd700');g.addColorStop(.7,'#ff0066');g.addColorStop(1,'#2d004d')}else{g.addColorStop(0,'#fff');g.addColorStop(.22,s.color);g.addColorStop(1,darken(s.color,40))}ctx.fillStyle=g;ctx.fill();ctx.strokeStyle='rgba(255,255,255,.38)';ctx.lineWidth=3;ctx.stroke();ctx.save();ctx.translate(r,r);ctx.rotate(a+arc/2);ctx.textAlign='right';ctx.textBaseline='middle';ctx.fillStyle='#fff';ctx.shadowColor='#000';ctx.shadowBlur=10;ctx.font=s.mystery?'900 56px Arial':'900 25px Arial';ctx.fillText(s.mystery?'🎁':s.name.toUpperCase(),r-70,0);ctx.restore()}ctx.beginPath();ctx.arc(r,r,170,0,Math.PI*2);ctx.fillStyle='#ffd766';ctx.fill();ctx.lineWidth=12;ctx.strokeStyle='#fff';ctx.stroke();ctx.fillStyle='#004aad';ctx.font='900 44px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('SCC',r,r-15);ctx.font='900 24px Arial';ctx.fillText('SPIN & WIN',r,r+33)}
function darken(hex,p){let n=parseInt(hex.slice(1),16),a=Math.round(2.55*p),R=(n>>16)-a,G=(n>>8&255)-a,B=(n&255)-a;return'#'+(0x1000000+(R<0?0:R)*0x10000+(G<0?0:G)*0x100+(B<0?0:B)).toString(16).slice(1)}
form.addEventListener('submit',e=>{e.preventDefault();$('displayPlayer').textContent=$('playerName').value.trim();$('displayDepartment').textContent=$('department').value.trim();$('displayPhone').textContent=$('phoneNumber').value.trim();reg.classList.remove('active');game.classList.add('active')});
$('nextPlayer').onclick=()=>{form.reset();game.classList.remove('active');reg.classList.add('active');overlay.classList.remove('show');spinBtn.disabled=false;spinning=false};$('closeWinner').onclick=()=>{overlay.classList.remove('show');spinning=false;spinBtn.disabled=false};
spinBtn.onclick=()=>{if(spinning)return;spinning=true;spinBtn.disabled=true;const target=Math.random()*Math.PI*2+Math.PI*2*8;rotation+=target*180/Math.PI;canvas.style.transform=`rotate(${rotation}deg)`;setTimeout(evaluate,6400)};
function evaluate(){let rad=(rotation*Math.PI/180)%(Math.PI*2);if(rad<0)rad+=Math.PI*2;let pointer=(Math.PI*2-rad)%(Math.PI*2);let idx=Math.floor(pointer/arc)%total;let win=sections[idx];if(win.mystery&&Math.random()>.01)win=sections[(idx+1)%total];winnerPrize.textContent=win.name.toUpperCase();overlay.classList.add('show');burst(W/2,H/2-80,170);burst(W/2-230,H/2-30,90);burst(W/2+230,H/2-30,90);animateFX()}
function burst(x,y,n){const colors=['#ffd700','#ff3366','#00d4ff','#3bff6f','#fff','#ff8c00'];for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,v=Math.random()*8+2;particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:1,decay:Math.random()*.015+.01,size:Math.random()*5+2,color:colors[Math.floor(Math.random()*colors.length)]})}}
function animateFX(){fctx.clearRect(0,0,W,H);particles=particles.filter(p=>{p.x+=p.vx;p.y+=p.vy;p.vy+=.08;p.life-=p.decay;fctx.globalAlpha=Math.max(p.life,0);fctx.fillStyle=p.color;fctx.beginPath();fctx.arc(p.x,p.y,p.size,0,Math.PI*2);fctx.fill();return p.life>0});fctx.globalAlpha=1;if(particles.length)requestAnimationFrame(animateFX)}
function makeLeaves(){const box=$('leaves');for(let i=0;i<24;i++){let s=document.createElement('span');s.textContent=Math.random()>.5?'🍃':'🍂';s.style.left=Math.random()*100+'vw';s.style.animationDelay=Math.random()*9+'s';s.style.animationDuration=(7+Math.random()*8)+'s';box.appendChild(s)}}makeLeaves();drawWheel();
